config/routes.rb
Rails.application.routes.draw do
  namespace :admin, path: '/parmatouze1317' do
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
    get 'dashboard/new_image', to: 'dashboard#new_image', as: 'new_image'
    post 'dashboard/create_image', to: 'dashboard#create_image', as: 'create_image'
    get 'newsletter_subscribers', to: 'dashboard#newsletter_subscribers', as: 'newsletter_subscribers'
    resources :news_items

    resources :orders, only: [:index, :update, :destroy] do
      member do
        get :invoice_catherine, defaults: { format: :pdf }
        get :invoice_amelie, defaults: { format: :pdf }
      end
    end

    resources :artworks, only: [] do
      patch :toggle_publish, on: :member
    end
  end

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get '/parmatouze1317', to: redirect('/users/sign_in')

  resources :artworks do
    collection do
      get :portfolio
      get :boutique
      get :prestations
    end
  end

  resources :orders, only: [:new, :create, :show, :destroy] do
    member do
      delete :cancel, to: 'orders#cancel'
    end
  end
  resources :contacts, only: [:new, :create]
  get '/page_daccueil', to: 'pages#accueil'
  get '/a_propos', to: 'pages#about'
  get '/connect_stripe', to: 'stripe#connect', as: :connect_stripe
  get '/stripe_dashboard', to: 'stripe#dashboard', as: :stripe_dashboard
  post '/add_to_cart', to: 'carts#add', as: :add_to_cart
  post 'remove_from_cart', to: 'carts#remove', as: 'remove_from_cart'
  get '/mentions', to: 'pages#mentions'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resource :cart, only: [:show], path: '/panier' do
    get :checkout_info
    post :checkout_create_order
    get 'checkout_payment/:id', action: :checkout_payment, as: :checkout_payment
    get 'payment_intent/:id', to: 'carts#payment_intent', as: :payment_intent
  end

  resources :subscribers, only: [:create] do
    member do
      get :unsubscribe
    end
  end

  resources :newsletters, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      post :send_to_subscribers
      get :preview_email
    end
  end

  get '/artworks/:category/:sub_category', to: 'artworks#sub_category', as: 'artworks_category_sub_category'
  post '/webhooks/stripe', to: 'webhooks#stripe'

  resources :news_items, only: [:index, :show]
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  has_many_attached :images
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :require_admin!

  def index
    @newsletters = Newsletter.all
  end

  def show
  end

  def new
    @newsletter = Newsletter.new
  end

  def edit
  end

  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to preview_email_newsletter_path(@newsletter), notice: "Newsletter was successfully created."}
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: "Newsletter was successfully updated." }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @newsletter.destroy!

    respond_to do |format|
      format.html { redirect_to newsletters_path, status: :see_other, notice: "Newsletter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def send_to_subscribers
    @newsletter = Newsletter.find(params[:id])
    subscribers = Subscriber.active

    subscribers.each do |subscriber|
      NewsletterMailer.send_newsletter(subscriber, @newsletter).deliver_later
    end

    flash[:notice] = "Newsletter envoyée !"
    redirect_to admin_dashboard_path
  end

  def preview_email
    @newsletter = Newsletter.find(params[:id])
    @subscriber = Subscriber.new(email: "demo@example.com")

    render template: 'newsletter_mailer/send_newsletter', layout: false
  end

  private

  def set_newsletter
    @newsletter = Newsletter.find(params[:id])
  end

  def newsletter_params
    params.require(:newsletter).permit(:subject, :body, images: [])
  end

  def require_admin!
    unless current_user&.admin?
      redirect_to root_path, alert: "Accès réservé à l'administration."
    end
  end
end

app/views/newsletters/_form.html.erb
<%= simple_form_for(@newsletter, html: { multipart: true }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :subject, label: "Sujet" %>
    <%= f.input :body, label: "Message" %>

    <%= f.input :images, label:"Image(s)", as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-custom" %>
  </div>
<% end %>

app/views/newsletters/_newsletter.html.erb
<div id="<%= dom_id newsletter %>">
  <p>
    <strong>Subject:</strong>
    <%= newsletter.subject %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= newsletter.body %>
  </p>

</div>

app/views/newsletters/edit.html.erb
<h1>Editing newsletter</h1>

<%= render "form", newsletter: @newsletter %>

<br>

<div>
  <%= link_to "Show this newsletter", @newsletter %> |
  <%= link_to "Back to newsletters", newsletters_path %>
</div>

app/views/newsletters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Newsletters</h1>

<div id="newsletters">
  <% @newsletters.each do |newsletter| %>
    <%= render newsletter %>
    <p>
      <%= link_to "Show this newsletter", newsletter %>
    </p>
  <% end %>
</div>

<%= link_to "New newsletter", new_newsletter_path %>

app/views/newsletters/new.html.erb
<div class="p-5">
  <h1>Nouvelle newsletter</h1>

  <%= render "form", newsletter: @newsletter %>

  <br>

  <div>
    <%= link_to "Retour", admin_dashboard_path, class: "btn btn-custom" %>
  </div>
</div>

app/views/newsletters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @newsletter %>

<div>
  <%= link_to "Edit this newsletter", edit_newsletter_path(@newsletter) %> |
  <%= link_to "Back to newsletters", newsletters_path %>

  <%= button_to "Destroy this newsletter", @newsletter, method: :delete %>
</div>