config/routes.rb
Rails.application.routes.draw do
  namespace :admin, path: '/parmatouze1317' do
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
    get 'dashboard/new_image', to: 'dashboard#new_image', as: 'new_image'
    post 'dashboard/create_image', to: 'dashboard#create_image', as: 'create_image'
    get 'newsletter_subscribers', to: 'dashboard#newsletter_subscribers', as: 'newsletter_subscribers'
    resources :news_items

    resources :orders, only: [:index, :update, :destroy] do
      member do
        get :invoice_catherine, defaults: { format: :pdf }
        get :invoice_amelie, defaults: { format: :pdf }
      end
    end

    resources :artworks, only: [] do
      patch :toggle_publish, on: :member
    end
  end

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get '/parmatouze1317', to: redirect('/users/sign_in')

  resources :artworks do
    collection do
      get :portfolio
      get :boutique
      get :prestations
    end
  end

  resources :orders, only: [:new, :create, :show, :destroy] do
    member do
      delete :cancel, to: 'orders#cancel'
    end
  end
  resources :contacts, only: [:new, :create]
  get '/page_daccueil', to: 'pages#accueil'
  get '/a_propos', to: 'pages#about'
  get '/connect_stripe', to: 'stripe#connect', as: :connect_stripe
  get '/stripe_dashboard', to: 'stripe#dashboard', as: :stripe_dashboard
  post '/add_to_cart', to: 'carts#add', as: :add_to_cart
  post 'remove_from_cart', to: 'carts#remove', as: 'remove_from_cart'
  get '/mentions', to: 'pages#mentions'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resource :cart, only: [:show], path: '/panier' do
    get :checkout_info
    post :checkout_create_order
    get 'checkout_payment/:id', action: :checkout_payment, as: :checkout_payment
    get 'payment_intent/:id', to: 'carts#payment_intent', as: :payment_intent
  end

  resources :subscribers, only: [:create] do
    member do
      get :unsubscribe
    end
  end

  resources :newsletters, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      post :send_to_subscribers
      get :preview_email
    end
  end

  get '/artworks/:category/:sub_category', to: 'artworks#sub_category', as: 'artworks_category_sub_category'
  post '/webhooks/stripe', to: 'webhooks#stripe'

  resources :news_items, only: [:index, :show]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto">
  <div class="container text-center">
    <a href="https://www.instagram.com/la.parcelle.des.reves/" target="_blank">
      <i class="fa-brands fa-instagram" style="color: #1F2F40;"></i>
    </a>
    <p class="mb-0 mt-2">
      <%= link_to "CGV - Mentions Légales", mentions_path %><br>
      &copy; Amélie Barbedienne et Catherine Barbedienne
    </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #FCEADF; z-index: 1030;">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <span class="navbar-brand mx-auto fw-bold fs-4 d-lg-none">
      La Parcelle des Rêves
    </span>



    <div class="collapse navbar-collapse justify-content-center" id="mainNavbar">
      <ul class="navbar-nav align-items-center gap-lg-4">
        <li class="nav-item">
          <%= link_to 'À Propos', a_propos_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Prestations', prestations_artworks_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Portfolio', portfolio_artworks_path, class: 'nav-link' %>
        </li>


        <li class="nav-item d-none d-lg-block fw-bold fs-5 mx-4 text-dark">
          <h1><%= link_to 'La Parcelle des Reves', page_daccueil_path, class: 'text-decoration-none text-dark' %></h1>
        </li>

        <li class="nav-item">
          <%= link_to 'Actualités', news_items_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Boutique', boutique_artworks_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', new_contact_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>

    <div class="navbar-nav d-flex align-items-center" style="position: absolute; right: 3%; top: 50%; transform: translateY(-50%);">
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to admin_dashboard_path do %>
          <% if current_user.avatar_filename.present? %>
            <%= image_tag "user_avatars/#{current_user.avatar_filename}", class: "rounded-circle", alt: "Avatar User", width: 40, height: 40 %>
          <% else %>
            <%= image_tag "default_user_avatar.jpg", class: "rounded-circle", alt: "Avatar User", width: 40, height: 40 %>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to cart_path, class: "btn position-relative" do %>
          <i class="fa-solid fa-cart-shopping" style="font-size: 1.5rem;"></i>
          <span class="bg-custom-badge">
            <%= session[:cart].present? ? session[:cart].size : 0 %>
          </span>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>